export enum ActionTypesHome {
  GETACCOUNTS = '[HOME] Get Accounts',
  GETACCOUNTS_SUCCESS = '[HOME] Get Accounts Success',
  GETACCOUNTS_FAILURE = '[HOME] Get Accounts Failure',
  CREATE_NEW_ACCOUNT = '[HOME] Create New Account',
  CREATE_NEW_ACCOUNT_SUCCESS = '[HOME] Create New Account Success',
  CREATE_NEW_ACCOUNT_FAILURE = '[HOME] Create New Account Failure',
  CREATE_NEW_DEPOSIT_PAYMENT = '[HOME] Create New Deposit | Payment',
  CREATE_NEW_DEPOSIT_PAYMENT_SUCCESS = '[HOME] Create New Deposit | Payment Success',
  CREATE_NEW_DEPOSIT_PAYMENT_FAILURE = '[HOME] Create New Deposit | Payment Failure',
  CREATE_NEW_TRANSFER = '[HOME] Create New Transfer',
  CREATE_NEW_TRANSFER_SUCCESS = '[HOME] Create New Transfer Success',
  CREATE_NEW_TRANSFER_FAILURE = '[HOME] Create New TransferFailure',
  GETLATESTACCOUNTMOVEMENTS = '[HOME] Get Latest Account Movements',
  GETLATESTACCOUNTMOVEMENTS_SUCCESS = '[HOME] Get Latest Account Movements Success',
  GETLATESTACCOUNTMOVEMENTS_FAILURE = '[HOME] Get Latest Account Movements Failure',
  GET_CURRENT_MONTH_INCOMINGS_ACTION = '[HOME] Get Current Month Incoming',
  GET_CURRENT_MONTH_INCOMINGS_ACTION_SUCCESS = '[HOME] Get Current Month Incoming Success',
  GET_CURRENT_MONTH_INCOMINGS_ACTION_FAILURE = '[HOME] Get Current Month Incoming Failure',
  GET_CURRENT_MONTH_EXPENSES_ACTION = '[HOME] Get Current Month Expenses',
  GET_CURRENT_MONTH_EXPENSES_ACTION_SUCCESS = '[HOME] Get Current Month Expenses Success',
  GET_CURRENT_MONTH_EXPENSES_ACTION_FAILURE = '[HOME] Get Current Month Expenses Failure',

  GET_CURRENT_YEAR_EXPENSES_ACTION = '[EXPENSES] Get Current Year Expenses',
  GET_CURRENT_YEAR_EXPENSES_ACTION_SUCCESS = '[EXPENSES] Get Current Year Expenses Success',
  GET_CURRENT_YEAR_EXPENSES_ACTION_FAILURE = '[EXPENSES] Get Current Year Expenses Failure',
}
